# Enable ZMK display drivers
CONFIG_ZMK_DISPLAY=y
CONFIG_ZMK_DISPLAY_WORK_QUEUE_DEDICATED=y
CONFIG_ZMK_DISPLAY_STATUS_SCREEN_CUSTOM=y

# Disable standard OLED canvas widgets to allow the nice!view custom UI to draw
CONFIG_ZMK_DISPLAY_STATUS_SCREEN_BUILT_IN=n
